### ISSUE TITLE
Añadir funcionalidad para tildes

### ISSUE THREAD

**Issue by jgonzal-ull** [Adri-Hdez/Preln#1]
Buenos días,
sería muy interesante añadir la posibilidad de unificar los textos con tildes en espeñol. Para ello sería necesario que hubiera un parámetro que permitira activar una funcionalidad que transforme las vocales con tilde en vocales sin tilde. Es importante conservar el nivel de mayúsculas. Una volcal con tilde mayúsculas se transforma en una vocal sin tilde mayúsculas y lo mismo par ael caso de minúsculas.
De esta forma si el usuario quisiera que se hiciera la doble conversión debería llamar a lowercase + withoutaccent
Muchas gracias

**Comment by Adri-Hdez** [comment]
Buenas tardes,
muchas gracias por la recomendación. El issue ha sido implementado, lo encontrará en la siguiente versión de la librería.

Muchas gracias.
