### ISSUE TITLE
No module named 'nltk'

### ISSUE THREAD

**Issue by jgonzal-ull** [Adri-Hdez/Preln#5]
Buenos días,
con la versión 0.3.5 existen una dependencia con la librería nltk que no está bien resuelta. incluso haciendo una desisntalación completa y instalación nueva da el problema. Lo probé primero con el pip install preln --upgrade y no iba tampoco.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/2914547/177139057-baeae25b-f007-4e7d-9731-371eecd4d978.png">

`C:\Users\jgonzal>pip uninstall preln
Found existing installation: preln 0.3.5
Uninstalling preln-0.3.5:
  Would remove:
    c:\users\jgonzal\appdata\local\programs\python\python39\lib\site-packages\preln-0.3.5.dist-info\*
    c:\users\jgonzal\appdata\local\programs\python\python39\lib\site-packages\preln\*
Proceed (Y/n)? Y
  Successfully uninstalled preln-0.3.5

C:\Users\jgonzal>pip install preln
Collecting preln
  Using cached preln-0.3.5-py3-none-any.whl (10 kB)
Installing collected packages: preln
Successfully installed preln-0.3.5`

`PS C:\Users\jgonzal\Dropbox\BOB-NLP>  c:; cd 'c:\Users\jgonzal\Dropbox\BOB-NLP'; & 'C:\Users\jgonzal\AppData\Local\Programs\Python\Python39\python.exe' 'c:\Users\jgonzal\.vscode\extensions\ms-python.python-2022.8.1\pythonFiles\lib\python\debugpy\launcher' '36073' '--' 'c:\Users\jgonzal\Dropbox\BOB-NLP\test_nlp_espaniol.py' 
Traceback (most recent call last):
  File "c:\Users\jgonzal\Dropbox\BOB-NLP\test_nlp_espaniol.py", line 1, in <module>
    from Preln.preprocessing import Preprocessing
  File "C:\Users\jgonzal\AppData\Local\Programs\Python\Python39\lib\site-packages\Preln\preprocessing.py", line 6, in <module>
    from .core.tokenizer import tokenizer
  File "C:\Users\jgonzal\AppData\Local\Programs\Python\Python39\lib\site-packages\Preln\core\tokenizer.py", line 2, in <module>
    from nltk.tokenize import word_tokenize
ModuleNotFoundError: No module named 'nltk'
PS C:\Users\jgonzal\Dropbox\BOB-NLP>`

**Comment by Adri-Hdez** [comment]
Buenos días.
En la siguiente versión se creará un fichero **requeriments** el cual contendrá las dependencias del proyecto. Se añadirá la ejecución de este fichero en el setup, que instalará todos los módulos necesarios. Muchas gracias por el feedback.

Mientras tanto, si desea hacer uso de la librería ejecute el siguiente comando:
- _pip install nltk_

Saludos.

**Comment by jgonzal-ull** [comment]
Genial, muchas gracias, es importante añadir también la dependencia y las instrucciones para instalar el recurso nltk_data que no se instala automáticamente con el pip install nltk.

- PS C:\Users\jgonzal\Dropbox\BOB-NLP> python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.download("punkt")
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jgonzal\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
True
>>> quit()

**Comment by Adri-Hdez** [comment]
Buenas tardes.

Ya esta solucionado el error del módulo nltk, además del manejador del recurso nltk_data. Le recomendamos que haga un pip **install preln --upgrade** para actualizar a la última versión (v0.3.7-alpha)

Como siempre, muchas gracias por el feedback.
