### ISSUE TITLE
date_format_ bug

### ISSUE THREAD

**Issue by jgonzal-ull** [Adri-Hdez/Preln#6]
Hay un pequeño bug que da cuando se le llama con date=True y dentro de la cadena la fecha está separada por / en lugar de -
El problema está en esta parte del código, creo que se debe usar la variable acabada en "_" todo el rato 
![image](https://user-images.githubusercontent.com/2914547/177193344-26714baa-2290-49f1-b8b5-cf24977e02d7.png)

![image](https://user-images.githubusercontent.com/2914547/177193381-2f2ec88f-7af2-4545-a037-8c0087f61a5c.png)

**Comment by jgonzal-ull** [comment]
Me refería en la línas 36, 38, 39 y 40 usar siempre date_format_

**Comment by jgonzal-ull** [comment]
![image](https://user-images.githubusercontent.com/2914547/177193674-02ed29f2-939f-4d7b-8cb2-986c8b790cbd.png)

**Comment by Adri-Hdez** [comment]
Buenas tardes.

Ya se ha corregido el bug que impedía realizar el formateo de la fecha. Además gracias a esto, hemos encontrado otro bug, el cual no admitía fechas del tipo 1/1/2020, sino que solo admitía el formato 01/01/2020, ahora se pueden utilizar ambos.

Muchas gracias por el feedback.
