### ISSUE TITLE
Date limits bug

### ISSUE THREAD

**Issue by jgonzal-ull** [Adri-Hdez/Preln#7]
Buenos días, cuando se especifica la fecha hay que añadir algún tipo de patron para detectar que el día y el mes son válidos en rango. 
Si se especifica un formato fecha con fecha inválida la aplicación se sale de rango y da error. Un ejemplo es con la fecha "31/13/2022".
uede ter dos posibles soluciones con un try-catch o bien chequeando previamente los rangos antes de llamar a los diccionarios de indexación para construir los meses.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/2914547/177313987-06182d5f-bc0f-4b28-b2ca-d6dd8f274ad1.png">

**Comment by Adri-Hdez** [comment]
Buenas tardes.

Ya se ha arreglado el problema del "out of range", ahora dependiendo del mes, el rango numérico es variante. Además se ha implementado el método de eliminación numérica. De todas formas, si realiza un formateo completo, es decir, de 14-11-2020 a Viernes 14 de Noviembre de 2020, se recomienda no realizar la eliminación numérica por si se quiere conservar dichos números. De todas formas, en próximas versiones, se intentará solucionar este error (ya esta desarrollada la forma de afrontarlo).

Muchas gracias por el feedback, un saludo.
